#!/usr/bin/sh -efu

# read global configuration and functions
. vmaps.sh ||:

# read local configuration
. ./vmaps.conf ||:

MS2VMAP=~/mapsoft2/programs/ms2vmap/ms2vmap
SRC_VMAP_DIR=../map_hr/vmap
SRC_VMAP_EXT=vmap

for i in "$@"; do
  name=${i%.*}
  name=${name##*/}
  src="$SRC_VMAP_DIR/$name.$SRC_VMAP_EXT"
  dst="$VMAP_DIR/$name.$VMAP_EXT"
  if [ ! -f "$src" ]; then
    echo "can't find file: $src"
    continue
  fi

  ${MS2VMAP} --edit update_en.txt --keep_labels 50 "$src" -o "$dst"
done > untranslated.txt
